### PR TITLE
[MISC]: Update dependencies, update deprecated code and fix clippy lints

### PR DESCRIPTION
**Pull request by Uzaaft**
This PR updates the dependencies, update deprecated code, and fix clips lints. 
Also, I see that there are multiple places where `String` is used. Is this really needed, or could we change this to `&str`(which is the preferred way in rust)?
From my understanding, `String` is used when if we need to own the string data, and `&str` is used if we only need a view of a string. 
By the way, I am not a biologist  😅.

### CODE REVIEW

**Comment by rob-p** [comment]
Wow; thanks so much @Uzaaft!  Some of this has been addressed in develop.  Would you be able to rebase this on develop for a merge?

**Comment by Uzaaft** [comment]
Oh, I totally overlooked the develop branch, my bad!
I can close this PR, and open a new one to the develop branch.  I think that would be the smartest choice. @rob-p

**Comment by rob-p** [comment]
No worries!  That would be *awesome*.  And thanks for contributing!

**Comment by Uzaaft** [comment]
Fixing it right away.

**Pull request closed without merging**
